name: Auto Update Icons

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 1'

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Node.js dependencies
        run: bun install --no-save

      - name: Install PHP dependencies
        run: composer update --no-interaction --no-progress

      - name: Compile icons to resources directory
        run: ./vendor/bin/blade-icons-generate

      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          title: 'Icons Release ID:${{ github.run_number }}'
          body: 'Auto Update Icons ID:${{ github.run_number }} RUN_ID:${{ github.run_id }}'
          commit-message: 'feat: automated change Icons Release ID:${{ github.run_number }}'
          base: main
          branch: auto-update-icons
          delete-branch: true
