name: release version
on:
  workflow_dispatch:
      
permissions:
  contents: write
  issues: write
  pull-requests: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main
          pre_release_branches: stage
          default_prerelease_bump: false
          tag_prefix: "v"
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          draft: true
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
